apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-13T16:47:08Z"
  name: carts-canary
  resourceVersion: "1268580"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 33b39716-1dc8-11ea-bfe4-42010a8001bb
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
